# -*- mode: ruby -*-
# vi: set ft=ruby :
SERVICES = {
'lb' => { ip: '192.168.0.10', ports: { 22000 => 22 }, box: "bento/ubuntu-24.04" },
'app1' => { ip: '192.168.0.11', ports: { 22001 => 22 }, box: "bento/ubuntu-24.04" },
'app2' => { ip: '192.168.0.12', ports: { 22002 => 22 }, box: "bento/ubuntu-24.04" },
'database' => { ip: '192.168.0.13', ports: { 22003 => 22 }, box: "bento/ubuntu-24.04" },
'consul' => { ip: '192.168.0.14', ports: { 22004 => 22 }, box: "bento/ubuntu-24.04" }
}
Vagrant.configure("2") do |config|
  # SSH configuration: use host keys instead of Vagrant-generated
  config.ssh.insert_key = false
  config.ssh.verify_host_key = :accept_new # Requires manual "yes" for "The authenticity of host ... can't be established." on first connection
  config.ssh.private_key_path = [
    '~/.ssh/id_rsa',
    '~/.vagrant.d/insecure_private_key'
  ]
  
  SERVICES.each do |hostname, machine|
    config.vm.define hostname do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = hostname
      node.vm.network :public_network, ip: machine[:ip], bridge: "enp0s9"
      machine[:ports].each do |host_port, guest_port|
        node.vm.network "forwarded_port", guest: guest_port, host: host_port, id: "ssh"
      end
      
      # Copy public key to VM
      node.vm.provision 'file', 
        source: '~/.ssh/id_rsa.pub', 
        destination: '~/.ssh/authorized_keys'
      
      node.vm.provider :virtualbox do |vb|
        vb.name = "vagrant-#{hostname}"
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  end
end
