pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {
        stage('Prepare') {
            steps {
                echo "Starting deployment"
                sh 'ansible --version'
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                withCredentials([
		    sshUserPrivateKey(credentialsId: 'ansible-key', keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER'),
                    usernamePassword(credentialsId: 'db-creds', usernameVariable: 'DB_USER', passwordVariable: 'DB_PASS'),
		    sshUserPrivateKey(credentialsId: 'github-key', keyFileVariable: 'GH_KEY', usernameVariable: 'GH_USER')
		    string(credentialsId: 'bird-app-secret-key', variable: 'APP_SECRET' )
		]) {

                        sh """

			    COMMON_ARGS="-i aws_ec2.yaml -u ubuntu --private-key \$SSH_KEY --extra-vars 'database_user=\$DB_USER database_password=\$DB_PASS git_key=\$GH_KEY app_secret_key=\$APP_SECRET'"
                           echo "Deploying DB"
                           ansible-playbook ansible/database.yml \$COMMON_ARGS

                           echo "Deploying LB"
                           ansible-playbook ansible/loadbalancer.yml \$COMMON_ARGS

                          echo "Deploying Apps"
                          ansible-playbook ansible/apps.yml \$COMMON_ARGS 
                        """
                }
            }
        }
    }
}
